### ISSUE TITLE
Pokemon Black 2 - All Items cheat Info page needs to be updated

### ISSUE THREAD

**Issue by FastenedBrick25** [DeadSkullzJr/NDS-i-Cheat-Databases#1]
Pokemon Black 2 for the Item cheats (including the All items, All Berries and,  All medicines) The info page says Press L + R. This doesn't work. What you need to do is Press select and some arrows will appear around the name of the currently selected item. Then, press and hold L + R. While holding L + R, press select again and you will get all the everything.

**Comment by DeadSkullzJr** [comment]
> Pokemon Black 2 for the Item cheats (including the All items, All Berries and, All medicines) The info page says Press L + R. This doesn't work. What you need to do is Press select and some arrows will appear around the name of the currently selected item. Then, press and hold L + R. While holding L + R, press select again and you will get all the everything.

This is incorrect, nothing needs to be updated at all. The code(s) work in and outside the bad and its respective slots (I tested them). Pressing L + R in either instance populates the items in their respective slots immediately, no other buttons or requirements are needed. Something is up on your end.
